version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/react_js
      dockerfile: ./Dockerfile
    ports:
      - "4173:80"
    labels:
      - "com.example.project=front"
    networks:
      - app_network
    depends_on:
      - scylla_app

  scylla_app:
    build:
      context: ./backend/skyllago
      dockerfile: ./Dockerfile
    ports:
      - "10000:10000"
    env_file:
      - ./backend/skyllago/.env_example
    networks:
      - app_network
    depends_on:
      - scylla_bp

  scylla_bp:
    image: scylladb/scylla:6.2
    ports:
      - "9042:9042"
      - "19042:19042"
    volumes:
      - scylla_bp:/var/lib/scylla
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  scylla_bp:

networks:
  app_network:
