version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - '4173:80'
    labels:
      - 'com.example.project=front'
      
  scylla_app:
    build:
      context: .
      dockerfile: backend/skyllago/Dockerfile
    restart: unless-stopped
    ports:
    - "10000:10000"
    env_file:
      - backend/skyllago/.env_example

  scylla_bp:
    image: scylladb/scylla:6.2
    restart: unless-stopped
    command:
      - --smp=2
      - --memory=1GB
      - --overprovisioned=1
      - --developer-mode=1
      - --seeds=scylla_bp
    ports:
      - "9042:9042"
      - "19042:19042"
    volumes:
      - scylla_bp:/var/lib/scylla
volumes:
  scylla_bp: