vpc_cidr: "10.0.0.0/16"
public_subnets:
  - "10.0.1.0/24"
  - "10.0.2.0/24"
ami_id: "ami-12345678"
instance_type: "t2.micro"
tags:
  environment: "prod"
subnet_id: "subnet-0e0812f4f89e36dd7"
vpc_id:  "vpc-074f1677f6095ec51"